// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';
import TechList from './TechList/index.svelte';
import TechListNew from './TechListNew/index.svelte';

export const components = {
	biography: Biography,
	hero: Hero,
	rich_text: RichText,
	tech_list: TechList,
	tech_list_new: TechListNew
};
